services:
  infinity:
    image: michaelf34/infinity:latest
    ports:
      - "7997:7997"
    volumes:
      - infinity-data:/app/.cache
    restart: unless-stopped
    command: v2 --model-id BAAI/bge-m3 --port 7997 --device cuda --dtype float16 --batch-size 128
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - INFINITY_QUEUE_BATCH_WAIT_MULTIPLIER=0.0
      - INFINITY_BATCH_SIZE=1

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    ports:
      - "8085:80"
    environment:
      - TZ=Asia/Tokyo
    command: serve
    restart: unless-stopped

volumes:
  infinity-data: